### ISSUE TITLE
Import of arbitrary java classes does not work.

### ISSUE THREAD

**Issue by nicost** [micro-manager/pycro-manager#149] opened 2020-10-04 17:38 UTC
Following the example in the documentation (https://pycro-manager.readthedocs.io/en/latest/custom_java.html):

`magellan_api = self.construct_java_object('org.micromanager.magellan.api.MagellanAPI')`

I get:

```
 Traceback (most recent call last):
  File "C:\Users\NicoLocal\anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 3343, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-19-4938c3dc34dc>", line 1, in <module>
    coordinates = self.construct_java_object('org.micromanager.data.Coordinates')
 NameError: name 'self' is not defined
```

Exchanging "self" for "bridge" (was that the intent in the documentation?), I get:

```
Traceback (most recent call last):
  File "C:\Users\NicoLocal\anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 3343, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-20-66ca5d75c400>", line 1, in <module>
    coordinates = bridge.construct_java_object('org.micromanager.data.Coordinates')
  File "C:\Users\NicoLocal\anaconda3\lib\site-packages\pycromanager\core.py", line 190, in construct_java_object
    raise Exception('No valid java constructor found with classpath {}'.format(classpath))
Exception: No valid java constructor found with classpath org.micromanager.data.Coordinates
```

which could be related to issue #52 (Coordinates is a class with a private constructor and only static methods).

**Comment by henrypinkard** [comment] 2020-10-04 23:22
Yes, that was a typo in the docs (fixed now).

And yes again, it is a duplicate of #52. Coords has no public constructors, so Java reflection doesn't find anything to call. Maybe just make its constructor public as a quick workaround?

**Comment by henrypinkard** [comment] 2020-10-05 14:45
Closing since #52 is same underlying issue

**Closed by henrypinkard** 2020-10-05 14:45 UTC
