### ISSUE TITLE
Java CPU usage increases with sequential acquisitions

### ISSUE THREAD

**Issue by dpshepherd** [micro-manager/pycro-manager#285] opened 2021-05-07 05:35 UTC
### Bug report

**Bug summary**

Java CPU usage increases when running sequential acquisitions. This is new behavior. I went back to an older nightly build, but acquisitions do not start with those for some reason. I can't figure out when this change would have occurred. The Java CPU usage persists even after the acquisitions finish.

**Code for reproduction**

```

import numpy as np 
from pycromanager import Acquisition

events = []
for index, z_um in enumerate(np.arange(start=0, stop=10, step=0.5)):
    evt = {
            #'axes' is required. It is used by the image viewer and data storage to
            #identify the acquired image
            'axes': {'z': index},

            #the 'z' field provides the z position in µm
            'z': z_um}
    events.append(evt)

for i in range(5):
  with Acquisition('/path/to/storage', 'testacq') as acq:
      acq.acquire(events)
  acq = None
```

**Expected outcome**

Java CPU usage should drop after each acquisition finishes and cleans up. 

**Actual outcome**

Java CPU usages increase by the amount one acquisition uses each time. CPU usage stays high, even once the acquisitions are finished.

**Version Info**

  * Operating system: Windows 10 64-bit
  * pycromanager version: 0.12.8
  * MicroManager version: Tested with nightly builds from 20210426 -> 20210506.
  * Python version: 3.8
  * Python environment: command line and VS Code

**Comment by henrypinkard** [comment] 2021-05-07 15:42
I think someone else reported something similar on image.sc. I'm not able to reproduce on MacOS with demo config though. And strangely enough, I don't see any changes to the java code between 4-26 and 5-06. Are you sure its not there 4-26? Is there anything suspiciously different in the core logs between the two versions? Might be able to take a look on a windows machine later today

**Comment by dpshepherd** [comment] 2021-05-07 15:57
The bug is there on 04-26. I also jumped back to 04-01, but the code hangs when I try to start an acquisition. I tried both using a `with` block and manually starting the acquisition.

I haven't had time to systematically go back between 04-26 and 04-01 yet to see when exactly the issue of the acquisition not starting shows up.

**Comment by dpshepherd** [comment] 2021-05-07 16:24
I just replicated on my Windows 10 laptop as well with newest nightly build of MM (05-06) and pycromanager 0.12.8. The Java CPU use goes up and stays high after I run the above code block. I'm going to start backtracking to see if I can figure out when this started.

**Comment by dpshepherd** [comment] 2021-05-07 16:39
The high Java CPU usage starts with nightly build 04-15. Not present in 04-13.

**Comment by dpshepherd** [comment] 2021-05-07 20:05
Any thoughts on a quick fix for this? We can't use the older nightly build with our actual hardware (not entirely sure why - but related to some driver work Hamamatsu did). I tried using the 04-13 Pycromanager, AcqEngJ, etc... .jar files with the 05-06 build, but pycro-manager can't open the bridge.

**Comment by henrypinkard** [comment] 2021-05-07 23:30
Fixed it and merged so should be in new nightly builds. You can swap in the new NDTiff in the meantime. These now have a different home: https://s01.oss.sonatype.org/#nexus-search;quick~micro-manager

**Closed by henrypinkard** 2021-05-07 23:30 UTC
Labels: bug

**Comment by dpshepherd** [comment] 2021-05-08 15:15
We ran 8 sequential acquisitions last night and CPU usage went as expected. Thank you for the fast fix!
