### ISSUE TITLE
hook_fn troubles

### ISSUE THREAD

**Issue by kdmarchuk** [micro-manager/pycro-manager#277] opened 2021-04-14 18:00 UTC
Hi Henry. Working on the new instrument (finally). Trying to use the `hook_fn` to control a stepper motor outside of MM as a focus correction drive. 

I think I'm doing something wrong trying to utilize the` hook_fn`, but I'm not sure what.

```
from pycromanager import Bridge
from pycromanager import Acquisition, multi_d_acquisition_events


bridge = Bridge()
core = bridge.get_core()


def hook_fn(event):    
    return event

with Acquisition(directory='D:\Kyle', name='test', pre_hardware_hook_fn=hook_fn) as acq:
    events = multi_d_acquisition_events(z_start=0, z_end=10, z_step=1)
    acq.acquire(events)
```

Running this code, the acquisition window launches, then the code hangs without an image acquisition. I need to restart the Python kernal and MM. Removing ` pre_hardware_hook_fn=hook_fn` everything works fine. Same issues when I'm actually controlling the stepper motor.

I've also tried 
` post_hardware_hook_fn=hook_fn` 
` post_camera_hook_fn=hook_fn` 

The above was run:
Micro-Manager 2.0.0-gamma1 202010413
Demo config (also tested on a working instrument config)
Python 3.8.5
Pycromanager: 0.12.8 (`pip install pycromananager --upgrade` this morning)
Windows 10
PyCharm Community 2020.3.5 and Spyder IDE

I'm sure I'm just an idiot. Thanks for the help!
Kyle

**Comment by henrypinkard** [comment] 2021-04-14 18:11
Hey, glad to hear you're finally able to get it going. Your code looks right to me. This doesn't reproduce for me using latest code (on Mac) using pycharm. It's possible its a windows-only bug. I don't have a windows setup going right now because I'm transitioning computers, but maybe I could remote control yours to test it out.

Before we do that though , could you try `Acquisition(debug=True, core_log_debug=True...`? This will print what its doing both to the python console and the micro-manager core log. Maybe there is something suspicious in one of those. You could also try `Acquisition(process=True`, which will try to run the hook on a separate process rather than a separate thread.

**Comment by kdmarchuk** [comment] 2021-04-14 18:32
More like getting it started, but it's something.

```
with Acquisition(directory='D:\Kyle', name='test', pre_hardware_hook_fn=hook_fn, process=True) as acq:
    events = multi_d_acquisition_events(z_start=0, z_end=10, z_step=1)
    acq.acquire(events)
```
Hangs as the previous examples.

```
with Acquisition(directory='D:\Kyle', name='test', pre_hardware_hook_fn=hook_fn, debug=True, core_log_debug=True) as acq:
    events = multi_d_acquisition_events(z_start=0, z_end=10, z_step=1)
    acq.acquire(events)
```
Hangs and doesn't write anything to the console. I don't think it wrote anything relevant to the CoreLog below either...

We've started using AnyDesk for remote sessions since TV got mad at us during COVID...

2021-04-14T11:27:53.486470 tid12068 [IFO,LogManager] Enabled primary log file C:\Program Files\Micro-Manager-2.0gamma\CoreLogs\CoreLog20210414T112753_pid8480.txt
2021-04-14T11:27:53.486470 tid12068 [IFO,App] User: bidcadmin
2021-04-14T11:27:53.486470 tid12068 [IFO,App] Host: PathBIDC06
2021-04-14T11:27:53.486470 tid12068 [IFO,App] MM Studio version: 2.0.0-gamma1 20210413
2021-04-14T11:27:53.486470 tid12068 [IFO,App] MMCore version 10.1.1
2021-04-14T11:27:53.486470 tid12068 [IFO,App] Device API version 70, Module API version 10
2021-04-14T11:27:53.486470 tid12068 [IFO,App] Operating System: Windows 10 (amd64) 10.0
2021-04-14T11:27:53.486470 tid12068 [IFO,App] JVM: Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_152, 64-bit
2021-04-14T11:27:53.940204 tid10732 [IFO,App] Found plugin org.micromanager.display.inspector.internal.panels.intensity.IntensityInspectorPanelPlugin@2d5fc803
2021-04-14T11:27:53.940204 tid10732 [IFO,App] Found plugin org.micromanager.display.inspector.internal.panels.metadata.SummaryMetadataInspectorPanelPlugin@7548d8d2
2021-04-14T11:27:53.940204 tid10732 [IFO,App] Found plugin org.micromanager.display.inspector.internal.panels.metadata.PlaneMetadataInspectorPanelPlugin@1f383ff9
2021-04-14T11:27:53.940204 tid10732 [IFO,App] Found plugin org.micromanager.display.inspector.internal.panels.comments.CommentsInspectorPanelPlugin@5c6de82a
2021-04-14T11:27:53.941204 tid10732 [IFO,App] Found plugin org.micromanager.display.overlay.internal.overlays.PatternOverlayPlugin@6205cc87
2021-04-14T11:27:53.941204 tid10732 [IFO,App] Found plugin org.micromanager.display.inspector.internal.panels.overlays.OverlaysInspectorPanelPlugin@511a5455
2021-04-14T11:27:53.941204 tid10732 [IFO,App] Found plugin org.micromanager.display.overlay.internal.overlays.ScaleBarPlugin@575e108e
2021-04-14T11:27:53.941204 tid10732 [IFO,App] Found plugin org.micromanager.display.overlay.internal.overlays.TimestampPlugin@cc16554
2021-04-14T11:27:53.941204 tid10732 [IFO,App] Found plugin org.micromanager.acquisition.internal.DefaultMDAPlugin@40ecf1bf
2021-04-14T11:27:53.941204 tid10732 [IFO,App] Found plugin org.micromanager.display.internal.gearmenu.CopyToImageJItem@43d7bd0b
2021-04-14T11:27:53.941204 tid10732 [IFO,App] Found plugin org.micromanager.display.internal.gearmenu.ExportImagesItem@642a1f9f
2021-04-14T11:27:53.942203 tid10732 [IFO,App] Found plugin org.micromanager.display.internal.gearmenu.LineProfileItem@44805945
2021-04-14T11:27:53.943203 tid10732 [IFO,App] Found plugin org.micromanager.quickaccess.internal.controls.AutofocusButtons@2cf91bac
2021-04-14T11:27:53.943203 tid10732 [IFO,App] Found plugin org.micromanager.quickaccess.internal.controls.CloseAllButton@3fa1204d
2021-04-14T11:27:53.944202 tid10732 [IFO,App] Found plugin org.micromanager.quickaccess.internal.controls.ExposureTime@7ccfad84
2021-04-14T11:27:53.945202 tid10732 [IFO,App] Found plugin org.micromanager.quickaccess.internal.controls.LiveButton@35b72fdf
2021-04-14T11:27:53.947200 tid10732 [IFO,App] Found plugin org.micromanager.quickaccess.internal.controls.MDAButtons@404814d0
2021-04-14T11:27:53.948200 tid10732 [IFO,App] Found plugin org.micromanager.quickaccess.internal.controls.PresetButton@30115eeb
2021-04-14T11:27:53.948200 tid10732 [IFO,App] Found plugin org.micromanager.quickaccess.internal.controls.RefreshButton@307f32ad
2021-04-14T11:27:53.949199 tid10732 [IFO,App] Found plugin org.micromanager.quickaccess.internal.controls.SavedMDAButton@1e816c38
2021-04-14T11:27:53.949199 tid10732 [IFO,App] Found plugin org.micromanager.quickaccess.internal.controls.ScriptButton@5e20032c
2021-04-14T11:27:53.950199 tid10732 [IFO,App] Found plugin org.micromanager.quickaccess.internal.controls.ShutterControl@4bd5547c
2021-04-14T11:27:53.950199 tid10732 [IFO,App] Found plugin org.micromanager.quickaccess.internal.controls.SnapButton@79c578ce
2021-04-14T11:27:53.950199 tid10732 [IFO,App] Found plugin org.micromanager.quickaccess.internal.controls.TextLabel@18d2b53e
2021-04-14T11:27:53.950199 tid10732 [IFO,App] Plugin loading took 904ms
2021-04-14T11:27:53.950199 tid12068 [IFO,App] Finished waiting for plugins to load
2021-04-14T11:27:57.502431 tid12068 [IFO,Core] Did unload all devices
2021-04-14T11:27:57.502431 tid12068 [IFO,Core] Did unload all devices
2021-04-14T11:27:57.507429 tid12068 [IFO,Core] Did load device DHub from DemoCamera; label = DHub
2021-04-14T11:27:57.508428 tid12068 [IFO,Core] Did load device DCam from DemoCamera; label = Camera
2021-04-14T11:27:57.508428 tid12068 [IFO,Core] Did load device DWheel from DemoCamera; label = Dichroic
2021-04-14T11:27:57.508428 tid12068 [IFO,Core] Did load device DWheel from DemoCamera; label = Emission
2021-04-14T11:27:57.508428 tid12068 [IFO,Core] Did load device DWheel from DemoCamera; label = Excitation
2021-04-14T11:27:57.508428 tid12068 [IFO,Core] Did load device DObjective from DemoCamera; label = Objective
2021-04-14T11:27:57.508428 tid12068 [IFO,Core] Did load device DStage from DemoCamera; label = Z
2021-04-14T11:27:57.508428 tid12068 [IFO,Core] Did load device DLightPath from DemoCamera; label = Path
2021-04-14T11:27:57.508428 tid12068 [IFO,Core] Did load device DXYStage from DemoCamera; label = XY
2021-04-14T11:27:57.508428 tid12068 [IFO,Core] Did load device DShutter from DemoCamera; label = Shutter
2021-04-14T11:27:57.508428 tid12068 [IFO,Core] Did load device DAutoFocus from DemoCamera; label = Autofocus
2021-04-14T11:27:57.508428 tid12068 [IFO,Core] Will initialize 11 devices
2021-04-14T11:27:57.508428 tid12068 [IFO,Core] Will initialize device DHub
2021-04-14T11:27:57.508428 tid12068 [IFO,Core] Did initialize device DHub
2021-04-14T11:27:57.508428 tid12068 [IFO,Core] Will initialize device Camera
2021-04-14T11:27:57.508428 tid12068 [IFO,Core] Did initialize device Camera
2021-04-14T11:27:57.508428 tid12068 [IFO,Core] Default camera set to Camera
2021-04-14T11:27:57.508428 tid12068 [IFO,Core] Will initialize device Dichroic
2021-04-14T11:27:57.508428 tid12068 [IFO,Core] Did initialize device Dichroic
2021-04-14T11:27:57.508428 tid12068 [IFO,Core] Will initialize device Emission
2021-04-14T11:27:57.509427 tid12068 [IFO,Core] Did initialize device Emission
2021-04-14T11:27:57.509427 tid12068 [IFO,Core] Will initialize device Excitation
2021-04-14T11:27:57.509427 tid12068 [IFO,Core] Did initialize device Excitation
2021-04-14T11:27:57.509427 tid12068 [IFO,Core] Will initialize device Objective
2021-04-14T11:27:57.509427 tid12068 [IFO,Core] Did initialize device Objective
2021-04-14T11:27:57.509427 tid12068 [IFO,Core] Will initialize device Z
2021-04-14T11:27:57.509427 tid12068 [IFO,Core] Did initialize device Z
2021-04-14T11:27:57.509427 tid12068 [IFO,Core] Will initialize device Path
2021-04-14T11:27:57.509427 tid12068 [IFO,Core] Did initialize device Path
2021-04-14T11:27:57.509427 tid12068 [IFO,Core] Will initialize device XY
2021-04-14T11:27:57.509427 tid12068 [IFO,Core] Did initialize device XY
2021-04-14T11:27:57.509427 tid12068 [IFO,Core] Default xy stage set to XY
2021-04-14T11:27:57.509427 tid12068 [IFO,Core] Will initialize device Shutter
2021-04-14T11:27:57.509427 tid12068 [IFO,Core] Did initialize device Shutter
2021-04-14T11:27:57.509427 tid12068 [IFO,Core] Default shutter set to Shutter
2021-04-14T11:27:57.509427 tid12068 [IFO,Core] Will initialize device Autofocus
2021-04-14T11:27:57.509427 tid12068 [IFO,Core] Did initialize device Autofocus
2021-04-14T11:27:57.509427 tid12068 [IFO,Core] Default autofocus set to Autofocus
2021-04-14T11:27:57.509427 tid12068 [IFO,Core] Finished initializing 11 devices
2021-04-14T11:27:57.509427 tid12068 [IFO,Core] Default camera set to Camera
2021-04-14T11:27:57.509427 tid12068 [IFO,Core] Default stage set to Z
2021-04-14T11:27:57.511426 tid12068 [IFO,Core] Did update system state cache
2021-04-14T11:27:57.515424 tid12068 [IFO,Core] Did update system state cache
2021-04-14T11:27:57.845230 tid12068 [IFO,App] EDTHangLogger: Started monitoring of EDT hangs
                                    [       ] [heartbeat timeout = 4500 ms, hang check interval = 1000 ms]
2021-04-14T11:27:58.261987 tid12068 [IFO,App] Rebuilding config group table
2021-04-14T11:27:58.262986 tid12068 [IFO,App] Finished rebuilding config group table
2021-04-14T11:27:58.277978 tid12068 [IFO,App] Startup script (C:\Program Files\Micro-Manager-2.0gamma\MMStartup.bsh) not present
2021-04-14T11:27:58.277978 tid12068 [IFO,App] Updating GUI; config pad = true; from cache = false
2021-04-14T11:27:58.280976 tid12068 [IFO,Core] Default autofocus set to Autofocus
2021-04-14T11:27:58.280976 tid12068 [IFO,Core] Did update system state cache
2021-04-14T11:27:58.282974 tid12068 [IFO,App] Rebuilding config group table
2021-04-14T11:27:58.282974 tid12068 [IFO,App] Finished rebuilding config group table
2021-04-14T11:27:58.282974 tid12068 [IFO,App] Finished updating GUI
2021-04-14T11:27:59.401322 tid12068 [IFO,App] Initialized ZMQ Server on port: 4827
2021-04-14T11:29:23.472543 tid12068 [IFO,App] EDTHangLogger: Stopping monitoring of EDT hangs
2021-04-14T11:29:23.472543 tid12068 [IFO,Core] Did unload all devices
2021-04-14T11:29:23.472543 tid12068 [IFO,Core] System reset
2021-04-14T11:29:23.495530 tid12068 [IFO,Core] Core session ended

**Comment by henrypinkard** [comment] 2021-04-14 18:58
Yeah there's nothing in there. Will email you about remote control

**Comment by henrypinkard** [comment] 2021-04-15 01:34
Traced down to some issue with Acquisition hooks in the java side of micromanager, which doesn't show up when running from source. Potentially related to ZMQ server? Added in core logging to these libraries so that this can be traced down further (https://github.com/micro-manager/micro-manager/pull/1191)

**Comment by TownJasonP** [comment] 2021-05-01 06:26
Hi there Henry,

I'm really enjoying using pycromanager so far, but I'm having a similar issue on Windows 10 (Micomanager2.0gamma-20210430, python 3.8.8, pycromanager 0.12.8) with acquisitions hanging when adding an image processing function; even a minimal function that's just returning the unaltered image and the metadata. Like Kyle, adding the debugging arguments doesn't seem to have any clear response. Did you guys find a solution?

**Comment by henrypinkard** [comment] 2021-05-02 16:15
Tracked it down to what seems like it might be a bug in Java itself. It works when running from source code, but not when running the compiled versions. Didn't have a chance to try to fix it yet (@kdmarchuk want to give that a try this week?). In the meantime, a workaround is to run the Java parts of pycromanager/micromanager from source as described [here](https://github.com/micro-manager/pycro-manager/issues/123)

**Comment by kdmarchuk** [comment] 2021-05-02 20:07
I'm sorta happy it's not just me with the hook issue.

Henry, I'm mostly free Wed and Fri. Want to email me your availability?

**Comment by henrypinkard** [comment] 2021-05-07 23:32
@TownJasonP I just remote controlled @kdmarchuk's system, and it seemed his issue had already been resolved in one of the intervening builds. Are you still seeing your problem if you update both micro-manager and pycro-manager?

**Closed** 2021-06-10 23:25 UTC
Labels: question
