### ISSUE TITLE
Potential Issue with Acquisition Notification

### ISSUE THREAD

**Issue by carlkesselman** [micro-manager/pycro-manager#760] opened 2024-04-15 17:24 UTC
I have the latest version of micromanager and pyro manager installed.  I'm getting a funny error in acquisition notification:

```
File "C:\Users\carl\Repos\pycro-manager\pycromanager\acquisition\acq_eng_py\main\acq_notification.py", line 94, in from_json
    return AcqNotification(json['type'],
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\carl\Repos\pycro-manager\pycromanager\acquisition\acq_eng_py\main\acq_notification.py", line 60, in __init__
    raise ValueError(f"Unknown milestone: {milestone}")
ValueError: Unknown milestone: pre_z_drive
```

I modified the Value error to see what the error was, and as you can see its pre_z_drive.

Any idea of what could be causing this?

Thanks,

Carl

**Comment by henrypinkard** [comment] 2024-04-15 17:42
Yes, caused by a new notification type being added and the tests being skipped. I will try to get a fix up today

**Comment by henrypinkard** [comment] 2024-04-15 21:44
Should be fixed in new version https://github.com/micro-manager/pycro-manager/pull/757

**Closed by henrypinkard** 2024-04-15 21:44 UTC
Labels: bug
