### ISSUE TITLE
How to convert the live preview image into Numpy array in real-time

### ISSUE THREAD

**Issue by objectc** [micro-manager/pycro-manager#187] opened 2020-11-23 23:19 UTC
I am trying to convert the live preview image into Numpy array. However, the function `get_raw_pixels ` was quite slow, it would cost more than 4 seconds to exact 2160 x 4096 x 4  pixels. There should be some way to do it much faster since the preview shows the FPS is 17. Any alternative way to achieve this? I do not have too many experiences in using Micro-Manager. Any help would be grateful.

My code was as follow:
``` Python
import numpy as np
from pycromanager import Bridge
import time

bridge = Bridge()
studio = bridge.get_studio()
snap_list = live_manager.snap(False)
img = snap_list.get(0)

start_time = time.time()
raw_pixels = img.get_raw_pixels()
print("--- time_profile ", "get raw pixels", " %.4f seconds ---" % (time.time() - start_time))
```
`--- time_profile get raw pixels  4.4569 seconds ---`

**Comment by henrypinkard** [comment] 2020-11-24 03:46
Same issue #90, I think. I looked into it a bit and it seems that there is a major slowdown caused by the library that pycromanager is using to serialize data to transmit it between Java and Python. Should be fixable, just need to swap in an alternative library. Until that happens, any alternative way of trying this will likely run into the same problem

**Comment by henrypinkard** [comment] 2020-11-27 17:56
Should be fixed with a 10-100x speedup in tomorrows nightly build

**Comment by henrypinkard** [comment] 2020-12-01 15:18
I'm guessing this is fixed for you now? Reopen if you run into something else

**Closed by henrypinkard** 2020-12-01 15:18 UTC
Labels: question
