### ISSUE TITLE
java.lang.NullPointerException error when calling dataset.has_image

### ISSUE THREAD

**Issue by oeway** [micro-manager/pycro-manager#77] opened 2020-08-24 09:29 UTC
Hi, I am following the example by doing:
```python
from pycromanager import Acquisition
with Acquisition('./test-pycromanager-dataset', 'test1', tile_overlap=10) as acq:

        acq.acquire({'row': 0, 'col': 0})
        acq.acquire({'row': 1, 'col': 0})
        acq.acquire({'row': 0, 'col': 1})

        dataset = acq.get_dataset()
        dataset.has_image(row=0, col=0, resolution_level=1)
        dataset.read_image(row=0, col=0, resolution_level=1)
```

And the acquisition seems to be working and I can get the files on disk, but I am getting the following error:
```
Exception                                 Traceback (most recent call last)
<ipython-input-1-79df877bec01> in <module>
      7 
      8         dataset = acq.get_dataset()
----> 9         dataset.has_image(row=0, col=0, resolution_level=1)
     10         dataset.read_image(row=0, col=0, resolution_level=1)

~/miniconda3/lib/python3.7/site-packages/pycromanager/data.py in has_image(self, channel, z, time, position, channel_name, resolution_level, row, col, **kwargs)
    506                 axes.put(key, kwargs[key])
    507             if row is not None and col is not None:
--> 508                 return self._remote_storage.has_tile_by_row_col(axes, resolution_level, row, col)
    509             else:
    510                 return self._remote_storage.has_image(axes, resolution_level)

~/miniconda3/lib/python3.7/site-packages/pycromanager/core.py in <lambda>(instance, signatures_list, *args)
    261                 params, methods_with_name, method_name_modified = _parse_arg_names(methodSpecs, method_name, convert_camel_case)
    262                 return_type = methods_with_name[0]['return-type']
--> 263                 fn = lambda instance, *args, signatures_list=tuple(methods_with_name): instance._translate_call(signatures_list, args)
    264                 fn.__name__ = method_name_modified
    265                 fn.__doc__ = "{}.{}: A dynamically generated Java method.".format(_java_class, method_name_modified)

~/miniconda3/lib/python3.7/site-packages/pycromanager/core.py in _translate_call(self, method_specs, fn_args)
    348 
    349         self._socket.send(message)
--> 350         return self._deserialize(self._socket.receive())
    351 
    352     def _deserialize(self, json_return):

~/miniconda3/lib/python3.7/site-packages/pycromanager/core.py in receive(self, timeout)
     95                 return reply
     96         message = json.loads(reply.decode('utf-8'))
---> 97         self._check_exception(message)
     98         return message
     99 

~/miniconda3/lib/python3.7/site-packages/pycromanager/core.py in _check_exception(self, response)
    100     def _check_exception(self, response):
    101         if ('type' in response and response['type'] == 'exception'):
--> 102             raise Exception(response['value'])
    103 
    104     def close(self):

Exception: java.lang.NullPointerException
```

**Comment by henrypinkard** [comment] 2020-08-24 15:50
I wasn't able to reproduce. Are you using latest pycro-manager and latest nightly build of micro-manager?

It looks like this is an exception on the Java side. Maybe the full stack trace should probably be in the core log (corelogs folder in MM install directory)?

**Comment by henrypinkard** [comment] 2020-08-24 16:51
Actually, I think I may have fixed this. Available in nightly build after [this merges](max_multi_res_index)

**Comment by oeway** [comment] 2020-08-24 17:26
Yes, I am using the latest pycro-manager and nightly build.
 This is the java part:
```
Exception: java.lang.NullPointerException
java.base/java.util.concurrent.ConcurrentHashMap.get(ConcurrentHashMap.java:936)
org.micromanager.multiresstorage.MultiResMultipageTiffStorage.hasTileByRowCol(MultiResMultipageTiffStorage.java:398)
java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
java.base/java.lang.reflect.Method.invoke(Method.java:566)
org.micromanager.internal.zmq.ZMQServer.runMethod(ZMQServer.java:294)
org.micromanager.internal.zmq.ZMQServer.parseAndExecuteCommand(ZMQServer.java:349)
org.micromanager.internal.zmq.ZMQServer.lambda$initialize$1(ZMQServer.java:97)
java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by henrypinkard** [comment] 2020-08-24 17:30
Yes I think that should be fixed with the PR above

**Comment by oeway** [comment] 2020-08-24 17:32
When can I get the nightly version? I just upgraded pycromanager to the master branch of this repo, it doesn't seem to work. Do I need also the nightly micro-manager?

**Comment by henrypinkard** [comment] 2020-08-24 18:04
Yes, you need latest micromanager too. In the mean time, you can manually update by droping in latest versions of NDTiffStorage.jar and PycromanagerJava.jar from[ here](https://dl.bintray.com/micro-manager/micro-manager/org/micro-manager/). You put these in the plugins folder in your MM Install (make sure to delete the old ones)

**Comment by henrypinkard** [comment] 2020-08-25 18:40
Fixed with next nightly:

https://github.com/micro-manager/micro-manager/pull/913

**Closed by henrypinkard** 2020-08-25 18:40 UTC
