### ISSUE TITLE
Installation issue with version mismatch between Java ZMQ server and Python Client

### ISSUE THREAD

**Issue by mdanderson03** [micro-manager/pycro-manager#32] opened 2020-05-21 16:51 UTC
I installed the pycro-manager package and the latest micromanager 2.0 gamma version as well as checking the box to run the server on 4827. I ran the test code:

 from pycromanager import Bridge

bridge = Bridge()
bridge.get_core()

and the output was:

![image](https://user-images.githubusercontent.com/48689483/82583845-a0cace00-9b61-11ea-9f75-842cfc44dd12.png)

**Comment by henrypinkard** [comment] 2020-05-21 16:53
This means that the Java side (Micro-manager v2.3) and the Python side (Pycro-manager v2.4) are using different versions. Try upgrading to the [latest nightly build of micro-manager](https://micro-manager.org/wiki/Micro-Manager_Nightly_Builds)

**Comment by mdanderson03** [comment] 2020-05-21 19:08
Thank you, that solved some of this issue. I have been downloading and trying different nightly builds and I have found a few things. May 16th 2020 through most recent build (May 20th 2020) is v2.5. Up to May 10th 2020 is v2.3 so v2.4 should be in between those builds. When I give one a try in between htose, I get a new error message: 

![image](https://user-images.githubusercontent.com/48689483/82596131-cf05d900-9b74-11ea-8a33-ecb3ac383798.png)

**Comment by henrypinkard** [comment] 2020-05-21 19:14
Hard for me to say about bugs on older version as I've fixed a lot of little things lately. Try getting both latest micro-manager and latest pycro-manager with  `pip install pycromanager --upgrade`. If bug still persists I can take a closer look

**Comment by mdanderson03** [comment] 2020-05-21 19:46
I updated my virtual environment with the latest pycromanager:

![image](https://user-images.githubusercontent.com/48689483/82599259-f3b07f80-9b79-11ea-8873-71677a47dcb6.png)

I downloaded and installed the latest micromanager 2.0 gamma:

![image](https://user-images.githubusercontent.com/48689483/82599330-10e54e00-9b7a-11ea-8a6c-4a80359db4a9.png)

and the result was:

![image](https://user-images.githubusercontent.com/48689483/82599433-45f1a080-9b7a-11ea-8461-f0dcf4a00a99.png)

Thanks you for looking into this Henry!

**Comment by henrypinkard** [comment] 2020-05-21 20:34
This is just from running

```
from pycromanager import Bridge

bridge = Bridge()
bridge.get_core()
```

Correct?

I think this may be an error that occurs when your python process exits, but it might not mess up anything since your code is done running. I will try to fix anyway, but maybe try running through one of the full examples and see if it works?

**Comment by henrypinkard** [comment] 2020-05-21 20:51
I just pushed a potential fix, can you pip install 0.2.3 and see if the error goes away?

**Comment by henrypinkard** [comment] 2020-05-21 21:02
Update: version 0.2.4

**Comment by mdanderson03** [comment] 2020-05-21 21:51
Yes, it is just the following code that did that:

from pycromanager import Bridge

bridge = Bridge()
bridge.get_core()

I haven't tried an example yet to see if it works. I will try that soon. I did update to 0.2.4 and ran it. A bunch did go away, but there is still an attribute error. 

![image](https://user-images.githubusercontent.com/48689483/82610078-bce36500-9b8b-11ea-8093-05a8e4d452f3.png)

**Comment by mdanderson03** [comment] 2020-05-21 21:56
I just tried the example: 
![image](https://user-images.githubusercontent.com/48689483/82610327-282d3700-9b8c-11ea-9771-a8ab9b164476.png)
 
and got no errors and a figure 1 popped up: 

![image](https://user-images.githubusercontent.com/48689483/82610383-43984200-9b8c-11ea-91a9-fa534c5904d9.png)

So I am thinking that since that worked that this issue might be fixed. Thanks Henry! You solved this super fast too.

**Comment by henrypinkard** [comment] 2020-05-21 22:44
I think I forgot to add in a small thing, could you try once more with 0.2.5?

**Comment by mdanderson03** [comment] 2020-05-22 13:07
Just gave it a try and I also downloaded and used the May 21st 2020 micromanager build. 

![image](https://user-images.githubusercontent.com/48689483/82669465-7df3f480-9c09-11ea-9ae4-778583bd7d4b.png)

and got:

![image](https://user-images.githubusercontent.com/48689483/82670567-661d7000-9c0b-11ea-993e-5a6f03260751.png)
![image](https://user-images.githubusercontent.com/48689483/82670687-995fff00-9c0b-11ea-9a96-2278fc90a8db.png)

**Comment by henrypinkard** [comment] 2020-05-22 15:07
Thanks for all the testing. I finally figured out how to reproduce on my own machine, and now this should be fixed by  https://github.com/micro-manager/pycro-manager/pull/33 and available in 0.2.6

**Comment by mdanderson03** [comment] 2020-05-22 15:14
No problem. I am excited to control my microscopes with this package. Just tested the update myself and all the errors are now gone. Thanks Henry!

**Comment by henrypinkard** [comment] 2020-05-22 15:26
Enjoy!

**Comment by henrypinkard** [comment] 2020-05-22 15:26
added original question to docs: https://github.com/micro-manager/pycro-manager/pull/34

**Closed by henrypinkard** 2020-05-22 15:26 UTC
Labels: documentation
