### ISSUE TITLE
Acquisition doesn't acquire images

### ISSUE THREAD

**Issue by impact27** [micro-manager/pycro-manager#42] opened 2020-06-04 08:41 UTC
With micromanager I can acquire a stack of 10 images:
![mm_interface](https://user-images.githubusercontent.com/6740194/83734273-0c776580-a64f-11ea-83bb-a5de2580cf0c.png)
I would like to do the same with pycromanager. I replaced the acquisition engine as instructed in https://github.com/micro-manager/pycro-manager/issues/41 and run this code:
```python
from pycromanager import Acquisition, multi_d_acquisition_events

if __name__ == '__main__': #this is important, don't forget it

    with Acquisition(directory='C:/Users/Quentin.Peter/Desktop/tmp0', name='acquisition_name') as acq:
        events = multi_d_acquisition_events(10)
        acq.acquire(events)
```
A folder is created (`C:/Users/Quentin.Peter/Desktop/tmp0/acquisition_name_1/Full resolution`) and the following windows appears:
![interface](https://user-images.githubusercontent.com/6740194/83734265-0aada200-a64f-11ea-8756-f1c852b59465.png)

But then nothing happens. The python code is stuck in `Acquisition.await_completion`. If I try to close the window, it asks if I want to `Finish acquisition?` and I I press OK, the python code finishes.

**Comment by henrypinkard** [comment] 2020-06-04 16:57
Seems like this was caused by a bug in Java that I still don't understand, but should be now fixed. Will be in Micro-manager nightly builds after (https://github.com/micro-manager/micro-manager/pull/822). In the mean time, you can replace all three of NDTiffStorage.jar, Pycromanager.jar, and AcqEngJ.jar with their latest versions, available [here](https://dl.bintray.com/micro-manager/micro-manager/org/micro-manager/)

**Comment by henrypinkard** [comment] 2020-06-05 15:11
Is this bug fixed?

**Comment by impact27** [comment] 2020-06-06 16:26
With 20200605 I still have the same issue.

**Comment by henrypinkard** [comment] 2020-06-06 19:13
Hmmm. Unfortunately I cannot reproduce this anymore on either Windows or OSX. Is it possible one of the older versions of the libraries remains behind? Maybe you could try installing 20200605 into its own new directory? I wonder also if anything suspicious shows up in your core log (in the CoreLogs folder in your mm install directory)

**Comment by impact27** [comment] 2020-06-07 14:58
I uninstalled micromanager, emptied the bin, and installed 20200606, and the issue persists (win10). The log is:
[CoreLog20200607T165530_pid19912.txt](https://github.com/micro-manager/pycro-manager/files/4742294/CoreLog20200607T165530_pid19912.txt)

**Comment by impact27** [comment] 2020-06-07 15:01
It is behaving exactly the same if I replace `acq.acquire(events)` by `acq.await_completion()`

**Comment by henrypinkard** [comment] 2020-06-07 15:21
I see near the top of the core log: `MM Studio version: 2.0.x dev`. Are you running micro-manager directly from the source code rather than the desktop application?

**Comment by henrypinkard** [comment] 2020-06-07 16:12
If so, I would guess that your project may be linking to an older version of the dependency used for writing data. The previous bug I fixed lived inside the NDTiffStorage.jar library. 

So the acquisition event is received, and the image is acquired, but it cannot save so it does not display. Ideally, this would throw an error, but unfortunately I couldn't get it to log an error, as it seemed to be bug within Java itself.

**Comment by impact27** [comment] 2020-06-07 16:46
> I see near the top of the core log: `MM Studio version: 2.0.x dev`. Are you running micro-manager directly from the source code rather than the desktop application?

I installed it from https://valelab4.ucsf.edu/~MM/nightlyBuilds/2.0.0-gamma/Windows/ and run from the start menu.

**Comment by impact27** [comment] 2020-06-07 16:52
The NDTiffStorage.jar in C:/Program file/Micro-Manager-2.0gamma/plugins/Micro-manager has version 0.2.6

**Comment by henrypinkard** [comment] 2020-06-07 17:17
That's strange. @nicost do you have any idea why `MM Studio version: 2.0.x dev` shows up when not running from source, and if this might be connected to library versions?

**Comment by henrypinkard** [comment] 2020-06-07 17:51
Actually, I think you might be right that the problem is somewhere in the acquisition events, because I don't see the information about images actually being acquired in your corelog.

I made new versions of both the python and java side with logging related to acquisition events. The python side is in pycromanager 0.3.2. This time run your acquisition with `debug=True` and it should print stuff about acquisition events as they go. The java side is available in 0.7.5 [here](https://dl.bintray.com/micro-manager/micro-manager/org/micro-manager/pycro-manager/PycroManagerJava/0.7.5/). Just drop in and replace as usual. The logging will automatically go into the core log.

**Comment by impact27** [comment] 2020-06-07 18:24
I got it to work by replacing `import multiprocessing` by `import multiprocessing.dummy as multiprocessing` in `acquire.py`

**Comment by nicost** [comment] 2020-06-07 19:47
> 
> 
> That's strange. @nicost do you have any idea why `MM Studio version: 2.0.x dev` shows up when not running from source, and if this might be connected to library versions?

Mine says:
2020-06-07T12:46:46.291727 tid11832 [IFO,App] MM Studio version: 2.0.0-gamma1 20200605
2020-06-07T12:46:46.291727 tid11832 [IFO,App] MMCore version 10.1.0
2020-06-07T12:46:46.291727 tid11832 [IFO,App] Device API version 69, Module API version 10
2020-06-07T12:46:46.291727 tid11832 [IFO,App] Operating System: Windows 10 (amd64) 10.0
2020-06-07T12:46:46.291727 tid11832 [IFO,App] JVM: Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_152, 64-bit

**Comment by henrypinkard** [comment] 2020-06-07 20:41
Ah okay great! Then that suggests this is purely on the Python side, and that you're right, the events never actually get sent over. Events are designed to be constantly pulled from `Acquisition._event_queue` on their own dedicated thread. I use `multiprocessing` for this instead of `threading`, with the logic that we wouldn't want to slow down the event sending because some other processing is holding the global interpreter lock. I've since learned that`multiprocessing` behaves differently on windows than unix with unexpected (to me) consequences (https://github.com/micro-manager/pycro-manager/issues/9).

Maybe this is another such instance. Still not sure why I didn't see it on windows though. Which version of Python are you using @impact27?

**Comment by impact27** [comment] 2020-06-08 11:05
I think the multiprocessing problem is unrelated to pycromanager so micro-manager/micro-manager#822 solved this issue. It runs with python 3.7.6

**Comment by henrypinkard** [comment] 2020-06-08 15:05
Glad you were able to figure it out. It's unfortunate that multiprocessing is so non-intuitive on windows. Might be worth thinking about alternatives. For acquisition events it would be pretty easy to swap in multiple threads instead of multiple processes, and I doubt there would much (if any) performance hit, but image processors and acquisition hooks run by the same mechanism, and if using both at the same time global interpreter lock blocking could become a problem. I made a new issue to think about this more (https://github.com/micro-manager/pycro-manager/issues/46). Let me know if you have any ideas.

**Comment by impact27** [comment] 2020-06-08 16:15
Multiprocessing.dummy is using threads so using threads would be easy as it has the same api as multiprocessing.

**Comment by impact27** [comment] 2020-06-09 06:55
Actually I think I was mistaken, the problem is with the editor I am using. I created a PR there (https://github.com/spyder-ide/spyder-kernels/pull/229). I think the multiprocessing part of the bug really doesn't have anything to do with micromanager.

**Comment by henrypinkard** [comment] 2020-06-09 15:40
Ok great. In that case maybe there's not so much of a motivation to switch to `threading` from `multiprocessing` after all

**Comment by jmmanley** [comment] 2020-06-19 14:20
Hi, I was super excited to see this tool! I seem to be having the same issue described originally by @impact27. Multi-d acquisition works in the desktop app for me, but not when I run the following script:

```
from pycromanager import Acquisition, multi_d_acquisition_events

if __name__ == '__main__':
        with Acquisition(directory='C:/Users/jmanley/Desktop/test_acq/', name='test_acq', debug=True) as acq:
            events = multi_d_acquisition_events(10)
            acq.acquire(events)
```

with `debug=True`, I get the following output:
```
connecting 4827
connecting 4827
binding 4828
got event(s): [{'axes': {'time': 0}}, {'axes': {'time': 1}}, {'axes': {'time': 2}}, {'axes': {'time': 3}}, {'axes': {'time': 4}}, {'axes': {'time': 5}}, {'axes': {'time': 6}}, {'axes': {'time': 7}}, {'axes': {'time': 8}}, {'axes': {'time': 9}}]
sent events
got event(s):
None
```
(FYI, I got an error with debug in [acquire.py line 20](https://github.com/henrypinkard/pycro-manager/blob/e0315ef1893a05ba0e9e4625e5bea23460b096b5/pycromanager/acquire.py#L21), so I changed to: `print('got event(s):', events)`)

The script completes, but no images seem to be acquired or saved. CoreLog: [CoreLog20200619T095812_pid11668.txt](https://github.com/micro-manager/pycro-manager/files/4805022/CoreLog20200619T095812_pid11668.txt)

I am using Windows, python 3.7.6, micromanager version 2.0.0-gamma1 20200618, pycromanager version 0.3.3 (and from source). Using `multiprocessing.dummy` didn't fix.

Any ideas what could be going on? Many thanks!

**Comment by henrypinkard** [comment] 2020-06-19 14:36
Not quite sure. What do you mean by "desktop app"? From an IDE? And then when it doesn't work, that's running the script from the command line?

**Comment by jmmanley** [comment] 2020-06-19 14:43
Thanks for the quick response! By desktop app, I just meant in the micromanager GUI application itself, where everything works fine. Yes, it is when I run the script in the command line that it doesn't work.

**Comment by henrypinkard** [comment] 2020-06-19 14:47
Got it. Those are actually running different libraries under the hood, so working in MM GUI doesn't tell us much. I think this issue might be on the Java side. Could you try running with different python setups to see if that changes anything? In addition to running script, you could try entering python on command line and typing each command in the script individually? And then maybe from an IDE like pycharm?

**Comment by henrypinkard** [comment] 2020-06-19 14:47
If none of those work I can add some more logging into the Java side

**Comment by henrypinkard** [comment] 2020-06-19 18:48
Just saw and fixed another bug that acquisitions can fail silently if there's not enough disk space. For performance reasons, the saving files allocate much more space than needed (4GB) before truncating. Is it possible you're saving to a HD that's almost full?

**Comment by jmmanley** [comment] 2020-06-19 19:07
No luck for me with pycharm or the command line: still no images saved and logs, etc. look the same. I tried saving to another disk with plenty of space and no luck there either. 

I agree it would be nice to log the Java side - would the relevant "receiver" of the messages be in the core micro-manager repo or here in the ZMQ Java classes?

**Comment by henrypinkard** [comment] 2020-06-19 19:29
It would be dispatched through the ZMQ Java classes to the [acquisition library](https://github.com/micro-manager/AcqEngJ.git), and eventually be saved by [this data writing library](https://github.com/micro-manager/NDTiffStorage), and displayed by [this viewer library](https://github.com/micro-manager/NDViewer.git).

Do you have experience with Java development?

**Comment by jmmanley** [comment] 2020-06-19 20:25
I only have a little experience with Java, so maybe above my head..

**Comment by henrypinkard** [comment] 2020-06-19 20:27
Okay, could I remote control your system with teamviewer to investigate?

**Comment by henrypinkard** [comment] 2020-06-29 16:25
@jmmanley still having an issue with this?

**Comment by jmmanley** [comment] 2020-06-30 01:08
Hey @henrypinkard, sorry for the delay! Just tried again. Not sure what’s changed, but things seem to be working with the latest nightly build! :)

**Closed** 2020-06-30 03:19 UTC
